---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes    
    when: ansible_distribution == 'Debian'

  - name: install-apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ['Debian','Ubuntu']

  - name: install php
    apt:
      name: php
      state: latest
    when: ansible_distribution == 'Debian'

  - name: update repository index CentOS
    dnf:
      update_cache: yes    
    when: ansible_distribution == 'CentOS'

  - name: install-apache2 package CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == 'CentOS'

  - name: install php CentOS
    dnf:
      name: php
      state: latest
    when: ansible_distribution == 'CentOS'

...
