---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes    

  - name: install-apache2 package
    apt:
      name: apache2
  
  - name: install php
    apt:
      name: php

...
